### ISSUE TITLE
Test package errors when using kong.Response.ExitStatus

### ISSUE THREAD

**Issue by elroy-haw** [Kong/go-pdk#119]
When the plugin uses `kong.Response.ExitStatus`, there are occasional issues that I ran into when using the `test` module. The issues are quite similar to https://github.com/Kong/go-pdk/issues/66.

```
=== RUN   TestPlugin
    test.go:579: Access
    test.go:579: Access
    test.go:232: Can't read method name
    test.go:579: Access
    test.go:579: Access
    test.go:232: Can't read method name
    test.go:579: Access
    test.go:232: Can't read method name
    test.go:232: Can't read method name
--- FAIL: TestPlugin (0.00s)

FAIL
```

Sometimes it panics with the following:
```
=== RUN   TestPlugin
    test.go:579: Access
--- PASS: TestPlugin (0.00s)
panic: Fail in goroutine after TestPlugin has completed

goroutine 21 [running]:
testing.(*common).Fail(0x1400027a4e0)
	/Users/elroy.haw/.asdf/installs/golang/1.18/go/src/testing/testing.go:817 +0xd4
testing.(*common).Errorf(0x1400027a4e0, {0x100ee6b38?, 0x14000223ea8?}, {0x0?, 0x1400004ef48?, 0x100ed6ea8?})
	/Users/elroy.haw/.asdf/installs/golang/1.18/go/src/testing/testing.go:934 +0x64
github.com/Kong/go-pdk/test.TestEnv.Errorf(...)
	/Users/elroy.haw/go/pkg/mod/github.com/!kong/go-pdk@v0.8.0/test/test.go:232
github.com/Kong/go-pdk/bridge/bridgetest.MockFunc.func1()
	/Users/elroy.haw/go/pkg/mod/github.com/!kong/go-pdk@v0.8.0/bridge/bridgetest/bridgetest.go:122 +0x1a4
created by github.com/Kong/go-pdk/bridge/bridgetest.MockFunc
	/Users/elroy.haw/go/pkg/mod/github.com/!kong/go-pdk@v0.8.0/bridge/bridgetest/bridgetest.go:118 +0xb0
```

To reproduce the issue:
```go
// main.go
package main

import (
	"github.com/Kong/go-pdk"
	"net/http"

	"github.com/Kong/go-pdk/server"
)

type Config struct {
}

func New() interface{} {
	return &Config{}
}

func (conf Config) Access(kong *pdk.PDK) {
	kong.Response.ExitStatus(http.StatusFound)
}

func main() {
	server.StartServer(New, "v0.0.1", 0)
}
```

```go
// main_test.go
package main

import (
	"testing"

	"github.com/Kong/go-pdk/test"
	"github.com/stretchr/testify/assert"
)

func TestPlugin(t *testing.T) {
	for i := 0; i < 5; i++ {
		env, err := test.New(t, test.Request{
			Method: "GET",
			Url:    "http://example.com?q=search&x=9",
		})
		assert.NoError(t, err)
		env.DoAccess(&Config{})
	}
}
```

Digging a little deeper to the `test` package, I think the reason this happens is because `kong.Response.ExitStatus` does not include any headers in the `kong_plugin_protocol.ExitArgs` and as such, the envState is not marked as finished [here](https://github.com/Kong/go-pdk/blob/v0.8.0/test/test.go#L429). My current workaround is to use `kong.Response.Exit` instead which works fine.

Version: 0.8.0

**Comment by StarlightIbuki** [comment]
Thanks for the reporting and analysis. Internally tracked: KAG-3813.

**Comment by leosunmo** [comment]
Also encountered this today with `kong.Response.ExitStatus(200)`.

**Comment by gszr** [comment]
Hi all - this issue is fixed as of `v0.10.2` - please give it a try!

**Comment by gszr** [comment]
Closed the issue, but feel free to reopen if the same issue persists. If you find a new one, please open a separate ticket.

**Comment by ricfeatherstone** [comment]
Seeing the same errors with v0.11.0

```
=== RUN   TestPlugin
    test.go:629: Access
    test.go:629: Access
    test.go:245: Can't read method name
    test.go:629: Access
    test.go:245: Can't read method name
    test.go:629: Access
    test.go:245: Can't read method name
    test.go:629: Access
    test.go:245: Can't read method name
--- FAIL: TestPlugin (0.00s)

FAIL
```
