### ISSUE TITLE
nginx worker stuck on shutdown when plugin panics

### ISSUE THREAD

**Issue by diefans** [Kong/go-pdk#57]
If there is a broken error handling in the plugin, the appropriate nginx process is stuck on shutdown
```
ps ax| rg nginx
4034477 ?        Ss     0:01 nginx: master process /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
4034739 ?        S      0:00 nginx: worker process is shutting down
4042041 ?        S      0:00 nginx: worker process is shutting down
4048195 ?        S      0:00 nginx: worker process is shutting down
4054000 ?        S      0:00 nginx: worker process
4054001 ?        S      0:00 nginx: worker process
4054002 ?        S      0:00 nginx: worker process
4054003 ?        S      0:00 nginx: worker process
4054004 ?        S      0:00 nginx: worker process
4054005 ?        S      0:00 nginx: worker process
4054006 ?        S      0:00 nginx: worker process
4054007 ?        S      0:00 nginx: worker process
4060470 pts/3    S+     0:00 rg nginx
```

corresponding panic: 
```
kong_1            | 2021/03/08 15:51:19 [info] 135#0: *7568 [go:149] panic: send on closed channel, context: ngx.timer
kong_1            | 2021/03/08 15:51:19 [info] 135#0: *7568 [go:149] goroutine 49 [running]:, context: ngx.timer
kong_1            | 2021/03/08 15:51:19 [info] 135#0: *7568 [go:149] github.com/Kong/go-pdk/bridge.PdkBridge.Ask(...), context: ngx.timer
kong_1            | 2021/03/08 15:51:19 [info] 135#0: *7568 [go:149]    /go/pkg/mod/github.com/!kong/go-pdk@v0.6.0/bridge/bridge.go:24, context: ngx.timer
kong_1            | 2021/03/08 15:51:19 [info] 135#0: *7568 [go:149] github.com/Kong/go-pdk/bridge.PdkBridge.AskString(0xc000066660, 0x7f9c317e2540, 0x1a, 0xc000184410, 0x1, 0x1, 0xc0001843f0, 0x3, 0x0, 0x0), context: ngx.timer
kong_1            | 2021/03/08 15:51:19 [info] 135#0: *7568 [go:149]    /go/pkg/mod/github.com/!kong/go-pdk@v0.6.0/bridge/bridge.go:120 +0xda, context: ngx.timer
kong_1            | 2021/03/08 15:51:19 [info] 135#0: *7568 [go:149] github.com/Kong/go-pdk/request.Request.GetQueryArg(...), context: ngx.timer
kong_1            | 2021/03/08 15:51:19 [info] 135#0: *7568 [go:149]    /go/pkg/mod/github.com/!kong/go-pdk@v0.6.0/request/request.go:132, context: ngx.timer
kong_1            | 2021/03/08 15:51:19 [info] 135#0: *7568 [go:149] bm-auth.Config.Access(0x7f9c317dba96, 0x7, 0x7f9c317ddee0, 0xf, 0x7f9c317e8481, 0x28, 0x7f9c317dc14a, 0x8, 0x0, 0xc00005d0e0), context: ngx.timer
kong_1            | 2021/03/08 15:51:19 [info] 135#0: *7568 [go:149]    /go-plugins/bm-authx/auth.go:274 +0xf47, context: ngx.timer
kong_1            | 2021/03/08 15:51:19 [info] 135#0: *7568 [go:149] main.(*PluginServer).HandleEvent.func1(0xc000066660, 0xc00000ec00, 0xc0000146c0, 0xc0000a4050), context: ngx.timer
kong_1            | 2021/03/08 15:51:19 [info] 135#0: *7568 [go:149]    /go/pkg/mod/github.com/!kong/go-pluginserver@v0.6.1/event.go:61 +0x65, context: ngx.timer
kong_1            | 2021/03/08 15:51:19 [info] 135#0: *7568 [go:149] created by main.(*PluginServer).HandleEvent, context: ngx.timer
kong_1            | 2021/03/08 15:51:19 [info] 135#0: *7568 [go:149]    /go/pkg/mod/github.com/!kong/go-pluginserver@v0.6.1/event.go:59 +0x236, context: ngx.timer
```

**Comment by diefans** [comment]
This seems to be an issue for https://github.com/kong/kong: I have my plugin automatically compiled and trigger a kong reload afterwards. So on every reload there is one nginx worker stuck with
```
❯ ps ax| rg nginx
1363083 ?        Ss     0:00 nginx: master process /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
1363298 ?        S      0:00 nginx: worker process is shutting down
1363780 ?        S      0:00 nginx: worker process
1363781 ?        S      0:00 nginx: worker process
1363782 ?        S      0:00 nginx: worker process
1363783 ?        S      0:00 nginx: worker process
1363784 ?        S      0:00 nginx: worker process
1363785 ?        S      0:00 nginx: worker process
1363786 ?        S      0:00 nginx: worker process
1363787 ?        S      0:00 nginx: worker process
1366486 pts/3    S+     0:00 rg nginx

~
❯ sudo strace -p 1363298
strace: Process 1363298 attached
write(4, "2021/03/09 08:13:47 [info] 30#0:"..., 82) = 82
epoll_pwait(11, [], 512, 234, NULL, 8)  = 0
read(22, 0x56041d03b380, 4096)          = -1 EAGAIN (Resource temporarily unavailable)
mprotect(0x7f4cbde30000, 65536, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f4cbde30000, 65536, PROT_READ|PROT_EXEC) = 0
epoll_pwait(11, [], 512, 10000, NULL, 8) = 0
read(22, 0x56041d03b380, 4096)          = -1 EAGAIN (Resource temporarily unavailable)
epoll_pwait(11, [], 512, 10000, NULL, 8) = 0
read(22, 0x56041d03b380, 4096)          = -1 EAGAIN (Resource temporarily unavailable)
epoll_pwait(11, ^Cstrace: Process 1363298 detached
 <detached ...>
```

**Comment by diefans** [comment]
I run kong==2.3.3 in a docker container

**Comment by diefans** [comment]
FYA: https://github.com/Kong/kong/issues/6904
