### ISSUE TITLE
Test library errors when using kong.Response.Exit

### ISSUE THREAD

**Issue by ctrox** [Kong/go-pdk#66]
I just gave the new test library a try and ran into an issue where a call to `kong.Response.Exit` in the plugin can cause errors in the testing library.

```bash
$ go test ./... -v -count=1
=== RUN   TestPlugin
    test.go:573: Access
    test.go:573: Access
    test.go:573: Access
    test.go:240: Can't read method name
    test.go:240: Can't read method name
    test.go:573: Access
    test.go:240: Can't read method name
    test.go:573: Access
    test.go:240: Can't read method name
--- FAIL: TestPlugin (0.00s)
FAIL
FAIL    plugintest      0.005s
FAIL
```
Occasionally it also produces a panic when running the test repeatedly:

```bash
$ go test ./... -v -count=1
=== RUN   TestPlugin
    test.go:573: Access
    test.go:573: Access
    test.go:573: Access
    test.go:240: Can't read method name
    test.go:240: Can't read method name
    test.go:573: Access
    test.go:240: Can't read method name
    test.go:573: Access
    test.go:240: Can't read method name
--- FAIL: TestPlugin (0.00s)
panic: Fail in goroutine after TestPlugin has completed

goroutine 50 [running]:
testing.(*common).Fail(0xc000102780)
        /usr/lib/golang/src/testing/testing.go:697 +0x125
testing.(*common).Errorf(0xc000102780, 0x88abac, 0x16, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/testing/testing.go:803 +0x93
github.com/Kong/go-pdk/test.TestEnv.Errorf(...)
        /home/cyrill/tools/golang/pkg/mod/github.com/!kong/go-pdk@v0.7.0-beta1.0.20210526164613-49a95960d27c/test/test.go:240
github.com/Kong/go-pdk/bridge/bridgetest.MockFunc.func1(0x9126f0, 0xc000312080, 0x90a1f8, 0xc00030e000)
        /home/cyrill/tools/golang/pkg/mod/github.com/!kong/go-pdk@v0.7.0-beta1.0.20210526164613-49a95960d27c/bridge/bridgetest/bridgetest.go:124 +0x267
created by github.com/Kong/go-pdk/bridge/bridgetest.MockFunc
        /home/cyrill/tools/golang/pkg/mod/github.com/!kong/go-pdk@v0.7.0-beta1.0.20210526164613-49a95960d27c/bridge/bridgetest/bridgetest.go:117 +0x65
FAIL    plugintest      0.008s
FAIL
```

Here is a minimal example to reproduce the issue:

```golang
// main.go
package main

import (
	"net/http"

	"github.com/Kong/go-pdk"
	"github.com/Kong/go-pdk/server"
)

type Config struct {
}

func New() interface{} {
	return &Config{}
}

func (conf Config) Access(kong *pdk.PDK) {
	kong.Response.Exit(http.StatusUnauthorized, http.StatusText(http.StatusUnauthorized), nil)
}

func main() {
	server.StartServer(New, "v0.0.1", 0)
}
```

```golang
// main_test.go
package main

import (
	"testing"

	"github.com/Kong/go-pdk/test"
	"github.com/stretchr/testify/assert"
)

func TestPlugin(t *testing.T) {
	for i := 0; i < 5; i++ {
		env, err := test.New(t, test.Request{
			Method: "GET",
			Url:    "http://example.com?q=search&x=9",
		})
		assert.NoError(t, err)
		env.DoHttps(&Config{})
	}
}
```

```
// go.mod
module plugintest

go 1.16

require (
	github.com/Kong/go-pdk v0.7.0-beta1.0.20210526164613-49a95960d27c
	github.com/stretchr/testify v1.5.1
)
```

Am I doing something wrong here? If I reuse the `env` and simply call `env.DoHttps(&Config{})` within the loop, the error still appears although way less frequently (~1 out of 20 test runs). But in an actual plugin that I'm currently writing I have to create different `env` instances per subtest, since I need to test with a bunch of different client headers.

**Comment by javierguerragiraldez** [comment]
Thanks for the report!  `kong.Response.Exit` is a special case since it terminates early, and the test environment has issues with the unexpectedly-closed pipe.  The errortrace is useful too.

**Comment by elroy-haw** [comment]
Hi @javierguerragiraldez, I came across a similar issue as this one (let me know if I should open another issue instead of commenting here).

`kong.Response.ExitStatus` does not include any headers in the `kong_plugin_protocol.ExitArgs` and as such, the envState is not marked as finished [here](https://github.com/Kong/go-pdk/blob/v0.8.0/test/test.go#L429). My current workaround is to use `kong.Response.Exit` instead.

**Comment by javierguerragiraldez** [comment]
> let me know if I should open another issue instead of commenting here

please do, this one is closed.   your case seems different too.
